"""
Configuration constants for the Chat Engine.
"""

MODEL_NAME = "Qwen/Qwen3-4B-Instruct-2507"
MAX_MODEL_LENGTH = 2048

KV_CACHE_DTYPE = "fp8_e5m2"
ENABLE_CHUNKED_PREFILL = True
GPU_MEMORY_UTILIZATION = 0.80
MAX_NUM_SEQS = 128

ENABLE_PREFIX_CACHING = True
NUM_SCHEDULER_STEPS = 10
MAX_NUM_BATCHED_TOKENS = 4096

RESPONSE_CACHE_MAX_SIZE = 16_384
